/*password print:- in this first we have to calculate the sum fron the given pattern
of the time is teh time is suppose 23:05 then the hour 23 denotes inintial time so the series
can be generated by the formula like 23 + 45 + 89 + 177 + 353 + 705 = 1392 as
for 1 it will be (2*23)-1=45
for 2 it will be (2*45)-1=89
and so on for n it would be (2*(n-1))-1 and then addind all
and from the sum obtained it will be 1392 as 0 it will be A,1-->B,2-->C,----,9-->J;
so the answer of the question is BDJC
int a0=23;*/
int anet=5;
int t=a0;
int sum=a0;
for(int i=1;i<=anet;i++) {
t=(2*t)-1;
sum=sum+t;
}
System.out.print(sum);
/*this code will run till sum and then by using the switch cases or if statements 
we can print the values.*/
